language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - composer selfupdate
  - composer install --prefer-source --dev
  - phpenv rehash

script:
  - make

after_success:
  - make scrutinizer
